- hosts: all
  user: ec2-user
  become: yes
  tasks:
    - name: install Apache
      yum: name=httpd state=latest

    - copy: src=./sources/index.html dest=/var/www/html/ owner=ec2-user group=ec2-user

    - copy: src=./sources/logo.png dest=/var/www/html/ owner=ec2-user group=ec2-user

    - name: enable & start service httpd
      systemd: name=httpd state=started enabled=true
